/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_micker_jnisafeimage_JNISafe */

#ifndef _Included_cn_micker_jnisafeimage_JNISafe
#define _Included_cn_micker_jnisafeimage_JNISafe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_micker_jnisafeimage_JNISafe
 * Method:    saveTextsToImage
 * Signature: (Landroid/content/Context;[Ljava/lang/String;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_cn_micker_jnisafeimage_JNISafe_saveTextsToImage
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     cn_micker_jnisafeimage_JNISafe
 * Method:    getDataFromImage
 * Signature: (Landroid/content/Context;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_micker_jnisafeimage_JNISafe_getDataFromImage
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
